name: "Check setup 1C:Executor"
on:
  push:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version: [stable]
        os: [macOS-latest]
    name: check executor
    steps:
    - uses: actions/checkout@v4

    - name: Установка 1С:Исполнитель
      uses: ./

      with:
        version: ${{ matrix.version }}
        token: ${{ secrets.DEVELOPER_1C_TOKEN }}

    - name: Проверка скрипта 1С:Исполнитель
      run: executor __tests__/fixtures/test.sbsl